version: '3'

services:
  db:
    build: ./mongo
    restart: always
    container_name: mongo-integration-tests-prisma
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DB: integration-tests
      MONGO_INITDB_COLLECTION: test
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
